// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"twitch-crypto-donations/internal/app/register"
	"twitch-crypto-donations/internal/config"
	"twitch-crypto-donations/internal/pkg/database"
	"twitch-crypto-donations/internal/pkg/environment"
	"twitch-crypto-donations/internal/pkg/router"
	"twitch-crypto-donations/internal/pkg/server"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) (*server.Server, error) {
	databaseDatabase := database.New()
	handler := register.New(databaseDatabase)
	handlers := router.Handlers{
		Register: handler,
	}
	routePrefix, err := environment.GetRoutePrefix()
	if err != nil {
		return nil, err
	}
	v := config.NewMiddlewares()
	engine := config.NewEngine(handlers, routePrefix, v)
	httpListenPort, err := environment.GetHTTPListenPort()
	if err != nil {
		return nil, err
	}
	serverServer := config.NewServer(engine, httpListenPort)
	return serverServer, nil
}
